//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCLScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanEventLog
    {
        public int ID { get; set; }
        public string SiteName { get; set; }
        public string EventKey { get; set; }
        public Nullable<System.DateTime> EventStamp { get; set; }
        public string EventDetail { get; set; }
        public string LogOrigin { get; set; }
        public Nullable<System.DateTime> LogCreationDate { get; set; }
        public Nullable<System.TimeSpan> LogCreationTime { get; set; }
    }
}
