//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCLScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanClientConfig
    {
        public int ConfigID { get; set; }
        public string PCName { get; set; }
        public string MainFolder { get; set; }
        public string ScanFolder { get; set; }
        public string PendingFolder { get; set; }
        public string HistoryFolder { get; set; }
        public string Validation { get; set; }
    }
}
